# Please keep the list alphabetically sorted!
# Fields:
#   * name (name surname)
#   * github (GitHub)
#   * email
#   * address
#   * description
#   * website

[[authors]]
name = "Filippo Costa"
github = "neysofu"
email = "filippo@neysofu.me"
description = "Maintainer"
website = "https://neysofu.me"

[[authors]]
name = "William Swinton"
description = "Logo (drawing of Plato)"
