= zenzi-version(1)
Filippo Costa
v{{{ VERSION }}}
:doctype: manpage
:manmanual: zenzi
:mansource: zenzi
:man-linkstyle: pass:[blue R < >]

== Name

zenzi version - Display the version of Zenzi which is installed.

== Synopis

*zenzi version* [--major] [--minor] [--patch] [--tags] [--build]

== Description

Prints to `STDOUT` the version of Zenzi which is locally installed. If no options
are given, then the full version is printed such as this:

    Zenzi 1.2.0-RC2-STABLE (6ED58A12)

If any options are given, only the specified information is displayed in
separate lines and in the specified order, e.g.:

    $ zenzi version --major --tags --build
    1
    RC2 SNAPSHOT
    6ED58A12

Tags are space-separated

== Options

--major
  Print the major version number.

--minor
  Print the minor version number.

--patch
  Print the patch version number.

--tags
  Print all the tags in a space-separated manner.

--build
  Print the build version number.

== Zenzi

Part of the **zenzi**(1) suite.
